config/routes.rb
Fanmapper::Application.routes.draw do

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'home#index'

   match "bars/:id/add_game/:game_id" => "bars#add_game", :as => :add_game

  resources :bars
  resources :teams, only: [:show]
  resources :games, only: [:index, :show]

  match "bars/:bar_id/add_game/:id" => "bars#add_game", :as => "add_game"

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :away_team_id, :game_at, :home_team_id, :home_team, :away_team  # home_team, away_team needed for seed file. Don't think it is necessary for production.
  has_many :bar_games
  has_many :bars, :through => :bar_games

  belongs_to :away_team, :class_name => "Team"
  belongs_to :home_team, :class_name => "Team"

  validate :uniqueness_of_matchup
  validates_presence_of :game_at, :home_team_id, :away_team_id

  def self.with_team(team_id)
    where("home_team_id = ? OR away_team_id = ?", team_id, team_id)
  end

  def self.for_week(week_number = nil)
    if week_number 
      week_diff = current_week - week_number
      week_start = beginning_of_nfl_week - week_diff.weeks
    else
      week_start = beginning_of_nfl_week
    end
    week_end = week_start + 1.week
    where(:game_at => week_start..week_end)
  end

  def self.current_week
    DateTime.now.cweek - 35  # this will need to be recalculated for the 2013 football season
  end

  def teams
    [self.home_team, self.away_team]
  end

private

  def uniqueness_of_matchup
    if self.away_team_id == self.home_team_id
      errors.add(:away_team_id, 'team cannot play itself')
    end
  end

  def self.beginning_of_nfl_week
    if DateTime.now.monday?
      Chronic.parse('next tuesday')
    elsif DateTime.now.tuesday?
      Time.now
    else
      Chronic.parse('last tuesday')
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :json, :html
  
  # this method is long.
  # Try to DRY this up w/ bars#index
  # returns json for bars...
  # /games/id/bars.json, # nested route
  # /bars.json  # => shallow route
  def show
    game = Game.find(params[:id])
    game_bar_list = game.bars

    @markers_info = []

    game_bar_list.each do |bar|
      @bar = bar
      @markers_info << render_to_string(:partial => 'bars/mini_bar_info', :layout => false)
    end
    render :json => { :local_bars => game_bar_list.coordinates(game),
                      :html_marker_info => @markers_info
                    }
  end

  # /games  => The games resource
  # RESTFUL = different representations
  # /games.html  => webpage that lists all games
  # /games.json => { :name => "Game 1"}
  # /games.js => give me the javascript representation
  def index
    @week = if params[:week]
      params[:week].to_i
    else
      Game.current_week
    end
    @games = Game.for_week(@week)
    respond_to do |format|
      format.js    # index.js.erb
    end
  end

end

app/views/games/_form.html.erb
<div class='unselected-matchup-table'>
  
 <h2 class="section-header">Upcoming Games</h2>
  <table class="table table-striped">
    <thead>
      <tr>        
        <th class="team-location">Away Team</th>
        <th class="team-location">Home Team</th>
        <th class="game-time">Game Time</th>
        <th class="option-header">Add Game</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
      <tr class="game-id-<%= game.id %>">
        <td class="team-location">
          <%= image_tag(game.away_team.small_logo_path) %>&nbsp;<%= "#{game.away_team.team_name}"%>
        </td>
        <td class="team-location">
          <%= image_tag(game.home_team.small_logo_path) %>&nbsp;<%= "#{game.home_team.team_name}" %>
        </td>
        <td class="game-time"><%= game.game_at.strftime('%A %l:%M %p - %m/%d')%></td>       
        <td class="option-add"><%= link_to 'Add', add_game_path(@bar, game), method: :post, :remote => true %></td>
        <td class="option-delete" style="display:none"><%= link_to "Remove", bar_path({:id => @bar, :game_id => game.id }), method: :delete, :remote => true %></td>        
      </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

app/views/games/_games.html.erb
<table id="teams" class="table table-striped">
  <% @games.each do |game| %>
    <tr class="update-bars" id="<%=game.id%>">
      <td>
        <%= image_tag(game.away_team.small_logo_path, :alt => '')%> 
         &nbsp;@&nbsp;
        <%= image_tag(game.home_team.small_logo_path, :alt => '')%> 
      </td>
      <td>
        <%= game.game_at.time.strftime('%A %l:%M %p') %> 
      </td>
    </tr>
  </a>
  <% end %>
</table>

app/views/games/_week_pager.html.erb
<ul class="pager" id="week_pager">
<li class="previous"><%= link_to 'Older', games_path(:week => week - 1), :remote => true %></li>
<%=" Week #{week}"%>
<li class="next"><%= link_to 'Newer', games_path(:week => week + 1), :remote => true %></li>
</ul>

app/views/games/index.js.erb
$('#game_list').html("<%= j render 'games/games', games: @games %>");
$('#week_pager').html("<%= j render 'games/week_pager', week: @week %>");