config/routes.rb
Fanmapper::Application.routes.draw do

  devise_for :users, path_names:  { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root to: 'home#index'

   match "bars/:id/add_game/:game_id" => "bars#add_game", :as => :add_game

  resources :bars
  resources :teams, only: [:show]
  resources :games, only: [:index, :show]

  match "bars/:bar_id/add_game/:id" => "bars#add_game", :as => "add_game"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>fabawag</title>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0EHZ-thmX12H-vtatONZE4BaE08hGOeA&sensor=false" type="text/javascript"></script>
    <%= filepicker_js_include_tag %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" /> 
  </head>
  <body class="<%= controller_name %>">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          </a>
          <a class="brand" href='/'>fabawag</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              
              <% if user_signed_in? %> <!--delete false when done testing !-->
                  <li><%= link_to "Signed in as #{current_user.name}", "#" %></li>
                  <% if current_user.bar_owner? %>  

                    <li class="dropdown">
                      <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
                        My Bars
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <% current_user.bars.each do |bar| %>  
                          <li><%= link_to bar.name, bar_path(bar), :class => 'dropdown-text'%></li>
                        <% end %>
                        <hr class='dropdown-hr'>
                        <li><%= link_to "Add New Bar", new_bar_path, :class => 'dropdown-text' %></li>
                      </ul>

                    </li>

                  <% end %>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                  <li><%= link_to "Sign In With Facebook", user_omniauth_authorize_path(:facebook)  %></li>
                  <li><%= link_to "List your bar", new_user_registration_path %></li>
              <% end %>
              <!--Fix Me !-->
              <% if flash[:notice] != nil %>
              <li><%= link_to flash[:notice], '' %></li>
              <% end %>
              <% if flash[:alert] != nil %>
              <li><%= link_to flash[:alert], '' %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class='container-bars'>
     <%= yield %>
     </div>
  </body>
</html>